# Generated by Django 5.0.6 on 2024-06-07 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('A', 'Available'), ('U', 'Used'), ('O', 'Out of Stock')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('landline', models.CharField(max_length=15)),
                ('phone_number1', models.CharField(max_length=15)),
                ('phone_number2', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('clinic_speciality', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('dentist', models.ForeignKey(limit_choices_to={'role': 'dentist'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_hour', models.TimeField(default='00:00:00')),
                ('end_hour', models.TimeField(default='00:00:00')),
                ('status', models.CharField(choices=[('D', 'Done'), ('M', 'Missed'), ('CP', 'Canceled by Patient'), ('CD', 'Canceled by Dentist'), ('R', 'Rescheduled'), ('A', 'Active'), ('P', 'Pending')], default='P', max_length=2)),
                ('comment', models.TextField()),
                ('dentist', models.ForeignKey(limit_choices_to={'role': 'dentist'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paymenet_mode', models.CharField(choices=[('CA', 'Cash'), ('CH', 'Check')], max_length=2)),
                ('source', models.CharField(choices=[('P', 'Patient'), ('I', 'Insurance')], max_length=100)),
                ('comment', models.TextField(max_length=1000)),
                ('current_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_user', to=settings.AUTH_USER_MODEL)),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Treatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teeth', models.IntegerField()),
                ('diagnostic', models.TextField(choices=[('Cavity', 'Cavity'), ('Gingivitis', 'Gingivitis'), ('Periodontitis', 'Periodontitis'), ('Abscess', 'Abscess'), ('Toothache', 'Toothache'), ('Bruxism', 'Bruxism'), ('Halitosis', 'Halitosis'), ('TMJ', 'TMJ'), ('Oral Cancer', 'Oral Cancer'), ('Dry Mouth', 'Dry Mouth'), ('Tooth Sensitivity', 'Tooth Sensitivity'), ('Mouth Sores', 'Mouth Sores'), ('Oral Thrush', 'Oral Thrush'), ('Tooth Erosion', 'Tooth Erosion'), ('Tooth Decay', 'Tooth Decay'), ('Tooth Loss', 'Tooth Loss'), ('Tooth Discoloration', 'Tooth Discoloration'), ('Tooth Fracture', 'Tooth Fracture'), ('Tooth Abscess', 'Tooth Abscess'), ('Toothache', 'Toothache'), ('Tooth Sensitivity', 'Tooth Sensitivity')], max_length=100)),
                ('notes', models.TextField(max_length=1000)),
                ('price', models.FloatField()),
                ('status', models.TextField(choices=[('D', 'Done'), ('P', 'Pending'), ('C', 'Canceled')], max_length=100)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.appointment')),
                ('consumable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.consumable')),
                ('dentist', models.ForeignKey(limit_choices_to={'role': 'dentist'}, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.patient')),
            ],
        ),
    ]
