# Generated by Django 5.0.6 on 2024-08-05 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='dentist',
            field=models.ForeignKey(limit_choices_to={'role': 'dentist'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='dentist',
            field=models.ForeignKey(limit_choices_to={'role': 'dentist'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.patient'),
        ),
        migrations.AddField(
            model_name='payment',
            name='current_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='current_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='dentist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.patient'),
        ),
        migrations.AddField(
            model_name='dentalservice',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic', to='clinic.speciality'),
        ),
        migrations.AddField(
            model_name='subcategoryservice',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinic', to='clinic.dentalservice'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='consumable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.consumable'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='dentist',
            field=models.ForeignKey(limit_choices_to={'role': 'dentist'}, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='treatment',
            name='diagnostic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.diagnostic'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.patient'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='teeth',
            field=models.ManyToManyField(to='clinic.tooth'),
        ),
        migrations.AddField(
            model_name='payment',
            name='treatment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.treatment'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='treatment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.treatment'),
        ),
    ]
