# Generated by Django 5.0.6 on 2024-08-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='teeth',
            field=models.ManyToManyField(blank=True, to='clinic.tooth'),
        ),
    ]
