# Generated by Django 5.0.6 on 2024-07-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_auto_20240718_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tooth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='teeth',
        ),
        migrations.AddField(
            model_name='treatment',
            name='teeth',
            field=models.ManyToManyField(to='clinic.tooth'),
        ),
    ]
