# Generated by Django 5.0.6 on 2024-08-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_auto_20240718_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tooth',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Teeth',
            },
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='teeth',
        ),
        migrations.AddField(
            model_name='treatment',
            name='teeth',
            field=models.ManyToManyField(to='clinic.tooth'),
        ),
    ]
