# Generated by Django 5.0.6 on 2024-08-05 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='end_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='start_date',
            field=models.DateTimeField(default=datetime.date.today, editable=False),
        ),
    ]
