# Generated by Django 5.0.6 on 2024-06-27 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_subcategoryservice_dentalservice_sous_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dentalservice',
            name='sous_categorie',
        ),
        migrations.AddField(
            model_name='subcategoryservice',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinic', to='clinic.dentalservice'),
        ),
    ]
