# Generated by Django 5.0.6 on 2024-08-06 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_alter_treatment_end_date_alter_treatment_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentalservice',
            name='has_subcategories',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime.today, editable=False),
        ),
    ]
