# Generated by Django 5.0.6 on 2024-07-24 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_tooth_remove_treatment_teeth_treatment_teeth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tooth',
            options={'verbose_name_plural': 'Teeth'},
        ),
    ]
