# Generated by Django 5.0.6 on 2024-08-06 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_dentalservice_has_subcategories_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dentalservice',
            old_name='service_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='subcategoryservice',
            name='has_subcategories',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SubSubCategoryService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinic', to='clinic.subcategoryservice')),
            ],
        ),
    ]
