# Generated by Django 5.0.6 on 2024-07-05 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_alter_patient_email'),
    ]

    operations = [
    ]
