# Generated by Django 5.0.6 on 2024-08-06 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_rename_service_name_dentalservice_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='treatment_name',
            field=models.CharField(default='Reprise de soin - Classe 2 - Distale', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='treatment',
            name='diagnostic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.diagnostic'),
        ),
    ]
