# Generated by Django 5.0.6 on 2024-07-05 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_auto_20240705_1552'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teeth', models.IntegerField()),
                ('notes', models.TextField(max_length=1000)),
                ('price', models.FloatField()),
                ('status', models.TextField(choices=[('D', 'Done'), ('P', 'Pending'), ('C', 'Canceled')], max_length=100)),
                ('consumable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.consumable')),
                ('dentist', models.ForeignKey(limit_choices_to={'role': 'dentist'}, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('diagnostic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.diagnostic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.patient')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.treatment'),
        ),
        migrations.DeleteModel(
            name='Treatement',
        ),
    ]
