# Generated by Django 5.0.6 on 2024-07-05 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_auto_20240705_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='treatment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.treatment'),
        ),
    ]
