# Generated by Django 5.0.6 on 2024-07-05 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0009_alter_appointment_treatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='start_date',
            field=models.DateField(default=datetime.date.today, editable=False),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='notes',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
