# Generated by Django 5.0.6 on 2024-07-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0010_treatment_end_date_treatment_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='status',
            field=models.TextField(choices=[('D', 'Done'), ('P', 'Pending'), ('C', 'Canceled')], default='P', max_length=100),
        ),
    ]
